name: Deploy job
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Angular deploy
      uses: honisekpatrik/wpub-rss-reader@master
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_configuration: production
        base_href: https://honisekpatrik.github.io/wpub-rss-reader/
        deploy_branch: deployment
        build_folder: dist/rss-citacka
